name: migue_admin
description: "Programa de escritorio para gestión de productos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # Gestión de Estado (Versiones Estables)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.5.1
  
  # Backend (Supabase)
  supabase_flutter: ^2.8.1
  
  # Utilidades
  intl: ^0.20.2 # <--- PAQUETE AÑADIDO
  image_picker: ^1.1.2 
  path: ^1.9.0
  
  # Desktop
  window_size: ^0.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Generadores (Versiones Estables)
  build_runner: ^2.4.11
  riverpod_generator: ^2.5.1
      
flutter:
  uses-material-design: true