name: migue_admin
description: "Programa de escritorio para gestiÃ³n de productos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.6.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  riverpod_annotation: ^2.5.1
  supabase_flutter: ^2.8.1
  window_size: ^0.1.0

dev_dependencies:

  # Generadores (Versiones Estables)
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.5.1

flutter:
  uses-material-design: true
  assets:
    - .env
